# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - asha-backend-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create & activate virtual environment, install backend deps
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Zip backend folder for deployment
        run: |
          cd ${{ github.workspace }}
          zip -r backend.zip backend

      - name: Upload backend artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-backend
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: python-backend

      - name: Unzip backend artifact
        run: unzip backend.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID}}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID}}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID}}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name:  'asha-backend-app'
          slot-name: 'Production'
          package:   './backend'
