name: Build and deploy Flask backend to Azure Web App - asha-backend-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create & activate virtualenv, install backend deps
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip **only** backend folder
        run: |
          cd ${{ github.workspace }}
          zip -r backend.zip backend

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-backend
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v4
        with:
          name: python-backend

      - name: Unzip backend
        run: unzip backend.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          client-secret:   ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy **backend/** to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name:        'asha-backend-app'
          package:         './backend'
